extends Level
class_name BanquetLevel

func _init() -> void:
	sequence = [
		[Event.SET_BOUND, false, -4, 0],
		[Event.DIALOGUE, "Magic Necktie", "Get ready, Guy. This place is crawling with goons."],
		[Event.WAIT_DIALOGUE_NEXT],
		[Event.QUEUE_SONG, preload("res://music/groovenotgoon5.tres")],
		[Event.ALIGN_MEASURE],
		[Event.PUSH_PIN],
		[Event.SET_BOUND, true, 23, 18],
		[Event.ADD_EXIT, 23],
		[Event.SPAWN, 0, true, [[GoonType.BASIC, 2]]],
		[Event.WAIT_BEATS, 1],
		[Event.SPAWN, 0, true, [[GoonType.BASIC, 3]]],
		[Event.WAIT_BEATS, 1],
		[Event.SPAWN, 0, true, [[GoonType.BASIC, 4]]],
		[Event.WAIT_BEATS, 1],
		[Event.SPAWN, 0, true, [[GoonType.RANGED, 5]]],
		[Event.WAIT_KILL],
		[Event.ALIGN_MEASURE],
		[Event.SPAWN, 0, true, [[GoonType.BASIC, 9], [GoonType.BASIC, 15], [GoonType.BASIC, 17], [GoonType.RANGED, 18], [GoonType.BASIC, 19]]],
		[Event.WAIT_BEATS, 1],
		[Event.PUSH_PIN],
		[Event.SPAWN, 1, true, [[GoonType.DASHING, -2]]],
		[Event.POP_PIN],
		[Event.WAIT_BEATS, 1],
		[Event.SPAWN, 0, true, [[GoonType.BASIC, 10]]],
		[Event.WAIT_BEATS, 1],
		[Event.SPAWN, 0, true, [[GoonType.BASIC, 11]]],
		[Event.WAIT_BEATS, 2],
		[Event.PUSH_PIN],
		[Event.SPAWN, 1, true, [[GoonType.DASHING, -2]]],
		[Event.POP_PIN],
		[Event.WAIT_BEATS, 6],
		[Event.PUSH_PIN],
		[Event.SPAWN, 1, true, [[GoonType.RANGED, -3], [GoonType.RANGED, 4]]],
		[Event.POP_PIN],
		[Event.WAIT_BEATS, 8],
		[Event.WAIT_BEATS, 16],
		[Event.PUSH_PIN],
		[Event.SPAWN, 1, true, [[GoonType.DASHING, -2]]],
		[Event.POP_PIN],
		[Event.JUMP, -4],
	]
