extends Level
class_name TutorialLevel

func _init() -> void:
	sequence = [
		[Event.SET_BOUND, false, -4, 0],
		[Event.ADD_SCENERY, -4, preload("res://levels/party_sign.tscn")],
		[Event.DIALOGUE, "Magic Necktie", "You've gotta dance to maintain your groove. All inputs you make in this game have to be on the beat."],
		[Event.WAIT_DIALOGUE_NEXT],
		[Event.DIALOGUE, "Magic Necktie", "Remember, dancing starts with the legs. Try pressing the RIGHT and LEFT arrow keys on the beat to move left and right."],
		[Event.WAIT_DIALOGUE_NEXT],
		[Event.QUEUE_SONG, preload("res://music/tutorial3.tres")],
		[Event.WAIT_BEATS, 4],
		[Event.ALIGN_MEASURE],
		[Event.PUSH_PIN],
		[Event.SPAWN, 0, true, [[GoonType.BASIC, 3]]],
		[Event.POP_PIN],
		[Event.DIALOGUE, "Magic Necktie", "Watch out for that goon. He'll attack you if you get close. When he winds up you can press UP or DOWN on the next beat to dodge up or down."],
		[Event.WAIT_DIALOGUE_NEXT],
		[Event.DIALOGUE, "Magic Necktie", "If you move into a goon you will instead hit them. Hit a goon twice to free them from the witch's spell."],
		[Event.WAIT_BEATS, 4],
		[Event.WAIT_KILL],
		[Event.HIDE_DIALOGUE],
		[Event.QUEUE_SONG, preload("res://music/tutorial4.tres")],
		[Event.ALIGN_MEASURE],
		[Event.DIALOGUE, "Magic Necktie", "You can also move and dodge with WASD or most controllers."],
		[Event.WAIT_DIALOGUE_NEXT],
		[Event.DIALOGUE, "You", "It's been a long time since I danced, but that sounds simple enough."],
		[Event.WAIT_DIALOGUE_NEXT],
		[Event.DIALOGUE, "Magic Necktie", "Defeating goons increases your groove. Getting hit by goons decreases it."],
		[Event.WAIT_DIALOGUE_NEXT],
		[Event.DIALOGUE, "Magic Necktie", "Lose your groove and you too will succumb to the spell."],
		[Event.WAIT_DIALOGUE_NEXT],
		[Event.ALIGN_MEASURE],
		[Event.PUSH_PIN],
		[Event.SPAWN, 0, true, [[GoonType.BASIC, 2]]],
		[Event.WAIT_BEATS, 1],
		[Event.SPAWN, 0, true, [[GoonType.BASIC, 5]]],
		[Event.WAIT_BEATS, 1],
		[Event.SPAWN, 0, true, [[GoonType.BASIC, 6]]],
		[Event.WAIT_BEATS, 1],
		[Event.SPAWN, 0, true, [[GoonType.BASIC, 8]]],
		[Event.POP_PIN],
		[Event.WAIT_KILL],
		[Event.ALIGN_MEASURE],
		[Event.PUSH_PIN],
		[Event.SPAWN, 0, true, [[GoonType.DASHING, -2]]],
		[Event.WAIT_BEATS, 2],
		[Event.SPAWN, 0, true, [[GoonType.BASIC, 3]]],
		[Event.WAIT_BEATS, 1],
		[Event.SPAWN, 0, true, [[GoonType.BASIC, 4]]],
		[Event.POP_PIN],
		[Event.WAIT_KILL],
		[Event.ALIGN_MEASURE],
		[Event.PUSH_PIN],
		[Event.SPAWN, 0, true, [[GoonType.BASIC, -1], [GoonType.BASIC, 2]]],
		[Event.POP_PIN],
		[Event.WAIT_KILL],
		[Event.ALIGN_MEASURE],
		[Event.PUSH_PIN],
		[Event.SPAWN, 0, true, [[GoonType.DASHING, -2], [GoonType.DASHING, 5]]],
		[Event.POP_PIN],
		[Event.WAIT_KILL],
		[Event.ALIGN_MEASURE],
		[Event.PUSH_PIN],
		[Event.SPAWN, 0, true, [[GoonType.RANGED, 5]]],
		[Event.WAIT_BEATS, 1],
		[Event.SPAWN, 0, true, [[GoonType.BASIC, 2]]],
		[Event.WAIT_BEATS, 2],
		[Event.SPAWN, 0, true, [[GoonType.BASIC, 3]]],
		[Event.POP_PIN],
		[Event.WAIT_KILL],
		[Event.ADD_EXIT, 7],
		[Event.ADD_SCENERY, 7, preload("res://levels/castle.tscn")],
		[Event.SET_BOUND, true, 7, 3]
	]
